wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.10.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693364232.683687
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 1
      - 23
      4: 3.8.17
      5: 0.15.9
      6: 4.10.0
      8:
      - 3
      - 5
output_dir:
  desc: null
  value: ./output_dir
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: IntervalStrategy.NO
prediction_loss_only:
  desc: null
  value: true
per_device_train_batch_size:
  desc: null
  value: 4
per_device_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./output_dir\runs\Aug30_05-56-03_DESKTOP-QN4SQLE
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: -1
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_steps:
  desc: null
  value: -1
save_total_limit:
  desc: null
  value: 0
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: ./output_dir
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: []
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
push_to_hub_model_id:
  desc: null
  value: output_dir
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
mp_parameters:
  desc: null
  value: ''
_n_gpu:
  desc: null
  value: 1
__cached__setup_devices:
  desc: null
  value: cuda:0
