wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.10.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693364768.766696
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.8.17
      5: 0.15.9
      6: 4.10.0
      8:
      - 3
      - 5
